apiVersion: apps/v1
kind: Deployment
metadata:
  name: stuhard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stuhard
  template:
    metadata:
      labels:
        app: stuhard
    spec:
      containers:
      - image: okteto.dev/stuhard:latest
        name: stuhard
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "53ea9377-6a57-47d3-ac64-34dbc57caacf"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "db7c22d7-dfa3-47db-8b3c-7c88fadcc94a"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
